### ISSUE TITLE
On clicking an option it scrolls to pin the widget on top of the page.

### ISSUE THREAD

**Issue by Erick331** [victoryhb/streamlit-option-menu#13]
Hi, First of all, thank you for this amazing widget. 

The problem I am facing is when I click any of the options in the widget it scrolls the page such that the widget is pinned at the top of the screen.

Before clicking.

![Screenshot 2022-04-22 at 6 15 21 PM](https://user-images.githubusercontent.com/35750225/164716902-1e95ec95-d58f-4456-a611-3918d3b623d1.png)

After clicking.

![Screenshot 2022-04-22 at 6 16 20 PM](https://user-images.githubusercontent.com/35750225/164717045-9051073c-2113-41e2-b018-ab8f24256025.png)

I will be looking forward to the solution.
Thanks

**Comment by wolfgang-koch** [comment]
I am facing the same problem and can't seem to solve it. Any idea?

**Comment by fgdvir** [comment]
Can you provide a code example for that?

**Comment by sshivaji** [comment]
I saw this issue too. It's not that hard to fix. The problem is in this line

https://github.com/victoryhb/streamlit-option-menu/blob/master/streamlit_option_menu/frontend/src/MyComponent.vue#L20

                    <a v-else href="#" class="nav-link" :class="{active: i == selectedIndex, 'nav-link-horizontal':isHorizontal}" 


Change the above line to <a href="javascript:void(0);" above

href="#" jumps to the top of the page. There are also other ways to solve the issue

**Comment by wolfgang-koch** [comment]
@sshivaji Yes, I figured it out, too.
I replaced href='#' with href='#dummy', because I didn't know any better. I guess your solution is cleaner.
